// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZX5XyrweB9LwDxqF9doKem6hhojeMh0',
    appId: '1:686533793342:web:4b45d7d7336cc6fef4e36f',
    messagingSenderId: '686533793342',
    projectId: 'flutter-cook-app',
    authDomain: 'flutter-cook-app.firebaseapp.com',
    storageBucket: 'flutter-cook-app.appspot.com',
    measurementId: 'G-2CPBSCXEVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGeJFc4oMCr1m-yQlq3QUzIRSv-abusNc',
    appId: '1:686533793342:android:e22c0feeb543cf79f4e36f',
    messagingSenderId: '686533793342',
    projectId: 'flutter-cook-app',
    storageBucket: 'flutter-cook-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqST0DLr9X1Y04Nh69WkhiXXChVI_hqM',
    appId: '1:686533793342:ios:107a41c4b5f10004f4e36f',
    messagingSenderId: '686533793342',
    projectId: 'flutter-cook-app',
    storageBucket: 'flutter-cook-app.appspot.com',
    iosBundleId: 'com.example.cookAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAqST0DLr9X1Y04Nh69WkhiXXChVI_hqM',
    appId: '1:686533793342:ios:107a41c4b5f10004f4e36f',
    messagingSenderId: '686533793342',
    projectId: 'flutter-cook-app',
    storageBucket: 'flutter-cook-app.appspot.com',
    iosBundleId: 'com.example.cookAppProject',
  );
}
